const FETCH_JOKE_REQUEST = "FETCH_JOKE_REQUEST";
const FETCH_JOKE_SUCCESS = "FETCH_JOKE_SUCCESS";
const FETCH_JOKE_FAIL = "FETCH_JOKE_FAIL";

const SET_JOKE_CATEGORY = "SET_JOKE_CATEGORY";

const jokeTypes = {
  FETCH_JOKE_REQUEST,
  FETCH_JOKE_SUCCESS,
  FETCH_JOKE_FAIL,
  SET_JOKE_CATEGORY,
};

export default jokeTypes;
