const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
const FETCH_DATA_FAIL = "FETCH_DATA_FAIL";

const ADD_FAVORITE_WORD_REQUEST = "ADD_WORD_FAVORITE_REQUEST";
const ADD_FAVORITE_WORD_SUCCESS = "ADD_FAVORITE_WORD_SUCCESS";
const ADD_FAVORITE_WORD_FAIL = "ADD_FAVORITE_WORD_FAIL";

const CHANGE_SELECTED_LANGUAGE = "SELECT_LANGUAGE";
const CHANGE_WORD = "CHANGE_WORD";
const RESET_WORD_DEFINITION_FORM = "RESET_WORD_DEFINITION_FORM";

const REMOVE_FAVORITE_WORD_REQUEST = "REMOVE_WORD_FAVORITE_REQUEST";
const REMOVE_FAVORITE_WORD_SUCCESS = "REMOVE_FAVORITE_WORD_SUCCESS";
const REMOVE_FAVORITE_WORD_FAIL = "REMOVE_FAVORITE_WORD_FAIL";

const GET_ALL_USER_FAVORITE_WORD_REQUEST = "GET_ALL_USER_FAVORITE_WORD_REQUEST";
const GET_ALL_USER_FAVORITE_WORD_SUCCESS = "GET_ALL_USER_FAVORITE_WORD_SUCCESS";
const GET_ALL_USER_FAVORITE_WORD_FAIL = "GET_ALL_USER_FAVORITE_WORD_FAIL";

const CHANGE_TOAST_STATE = "CHANGE_TOAST_STATE";

const wordTypes = {
  FETCH_DATA_REQUEST,
  FETCH_DATA_SUCCESS,
  FETCH_DATA_FAIL,
  ADD_FAVORITE_WORD_REQUEST,
  ADD_FAVORITE_WORD_SUCCESS,
  ADD_FAVORITE_WORD_FAIL,
  REMOVE_FAVORITE_WORD_REQUEST,
  REMOVE_FAVORITE_WORD_SUCCESS,
  REMOVE_FAVORITE_WORD_FAIL,
  GET_ALL_USER_FAVORITE_WORD_REQUEST,
  GET_ALL_USER_FAVORITE_WORD_SUCCESS,
  GET_ALL_USER_FAVORITE_WORD_FAIL,
  CHANGE_SELECTED_LANGUAGE,
  CHANGE_WORD,
  RESET_WORD_DEFINITION_FORM,
  CHANGE_TOAST_STATE,
};

export default wordTypes;
